name: ec2 automation

on: [push]

jobs:
    ec2-automation:
        runs-on: ubuntu-latest
        steps:

            - name: configuring aws credentials
              uses: aws-actions/configure-aws-credentials@main
              with: 
                  aws-region: us-east-1
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  


            - name: start ec2 instance
              run: |
                aws ec2 start-instances --instance-ids i-0a26903e45cc116c9
                aws ec2 wait instance-running --instance-ids i-0a26903e45cc116c9

            - name: ssh into instances
              run: |
                echo "${{ secrets.SSH_KEY }}" > key.pem
                ssh -o StrictHostKeyChecking=no -i key.pem vijal_dsouza_exam@ec2-100-24-210-82.compute-1.amazonaws.com
            
            - name: runnning shell
              run: |
                echo "workflow successfull"
